### ISSUE TITLE
How do I visualize data made up of BIDS?

### ISSUE THREAD

**Issue by iDestro** [bids-standard/bids-starter-kit#234] opened 2021-11-02 06:37 UTC

**Comment by Remi-Gau** [comment] 2021-11-02 10:50
I will close this as it is a duplicate of the issue in the bids specification repo and that has been answered there.

https://github.com/bids-standard/bids-specification/issues/922#issuecomment-957158611

**Closed by Remi-Gau** 2021-11-02 10:50 UTC
